### ISSUE TITLE
Getting transparent text once regex is used

### ISSUE THREAD

**Issue by crewshin** [kyle-n/HighlightedTextView#23]
I have a simple implementation for jwt patterns and just want to highlight each section of the token how jwt.io does. The issue I'm having is that as soon as I type the first ".", all text goes transparent. That first dot is the first bit that the regex pattern returns true. If I backspace past the dot, it fixes the text.

I also see this message repeat itself constantly until I remove text from the text editor: `2021-01-04 12:52:18.111796-0500 JWT Helper[8744:70419] -[__SwiftValue set]: unrecognized selector sent to instance 0x6000010659e0`

I'm sure it's something I'm doing but this implementation is so simple I don't see anything.

```swift
@State private var jwt: String = ""

var body: some View {
    HighlightedTextEditor(text: $jwt, highlightRules: .jwt) {
        
    }  onCommit: {
        
    }  onTextChange: { (text) in
        jwtData.jwt = text
        parseJWTData(jwt: jwt)
    }
}
```

```swift
import Foundation
import SwiftUI
import HighlightedTextEditor

fileprivate let jwtHeaderRegex = try! NSRegularExpression(pattern: "^([A-Za-z0-9-_=])+\\.", options: [])
fileprivate let jwtPayloadRegex = try! NSRegularExpression(pattern: "\\.([A-Za-z0-9-_=])+\\.*", options: [])
fileprivate let jwtSignatureRegex = try! NSRegularExpression(pattern: "\\.([A-Za-z0-9-_+/=])*$", options: [])

public extension HighlightedTextEditor {
    static let jwt: [HighlightRule] = [HighlightRule].jwt
}

public extension Sequence where Iterator.Element == HighlightRule {
    static var jwt: [HighlightRule] {
        [
            HighlightRule(pattern: jwtHeaderRegex, formattingRule: TextFormattingRule(key: .foregroundColor, value: Color("header"))),
            HighlightRule(pattern: jwtPayloadRegex, formattingRule: TextFormattingRule(key: .foregroundColor, value: Color("payload"))),
            HighlightRule(pattern: jwtSignatureRegex, formattingRule: TextFormattingRule(key: .foregroundColor, value: Color("signature"))),
        ]
    }
}
```

I should also mention that if I use the `.markdown` highlight rule it works fine.

Using: macOS 11.1 and Xcode 12.3 in a brand new SwiftUI test project.

**Comment by kyle-n** [comment]
Hm. I'm not sure what the problem is with this. Couple thoughts:

- I have not seen your color catalogue in Xcode, but I would check that, make sure these custom colors are set up correctly.
- I would try changing the values of your `TextFormattingRule`s to the built-in UIColor presets like `UIColor.red`. If those work then that narrows down the problem to the custom colors.
- I would rework your regex patterns. Check out the [documentation](https://developer.apple.com/documentation/foundation/nsregularexpression) for `NSRegularExpression`. Your current patterns affect the periods. `jwtPayloadRegex` will affect the whole string after the first period. I would check out the linked documentation, especially for look-ahead and look-behind. Those two concepts are what you need to fix these patterns. No worries if it takes a couple tries, regex is weird and dense.
- The error, I'm not sure about. Try the other steps and see if it persists.

**Comment by crewshin** [comment]
Hey thanks for the response. I'm suspecting the regex (colors definitely work), but both times it has given me the results I expected on regex101.com.

Here's my updated regex (probably still wrong hehe):
```swift
fileprivate let jwtHeaderRegex = try! NSRegularExpression(pattern: "^([A-Za-z0-9-_=])+(?=\\.)", options: [])
fileprivate let jwtPayloadRegex = try! NSRegularExpression(pattern: "(?<=\\.)([A-Za-z0-9-_=])+(?=\\.)", options: [])
fileprivate let jwtSignatureRegex = try! NSRegularExpression(pattern: "(?<=\\.)([A-Za-z0-9-_=])+$", options: [])
```

This is just a demo project I'm building to learn some SwiftUI so it doesn't really matter to me personally. But I just want to make sure I didn't discover some bug: https://github.com/crewshin/JWT if interested.

**Comment by kyle-n** [comment]
I checked out your project and tried one of the steps I had recommended. If the `TextFormattingRule`s for `jwt` use stock system colors like `NSColor.red`, the text is formatted as red. 

```swift
...
HighlightRule(pattern: jwtHeaderRegex, formattingRule: TextFormattingRule(key: .foregroundColor, value: NSColor.red)),
...
```

`TextFormattingRule`s set `NSAttributedString` values. Unfortunately, `NSAttributedString` formatting is untyped, so the only way to know what you can pass into a `TextFormattingRule` for a given attributed string value is to [check the documentation](https://github.com/kyle-n/HighlightedTextEditor#textformattingrule). 

In your case, `NSAttributedString` requires an `NSColor` to change string color. SwiftUI's `Color` will not work. If you're targeting Big Sur and above, there is a new API to convert `Color`s to `NSColor`.

**Comment by crewshin** [comment]
Pahahhaa. Thanks.

I'm not sure why I didn't think of digging deeper into the SwiftUI color stuff. Thanks again and sorry for the noise.
