### ISSUE TITLE
Configuring HighlightedTextEditor

### ISSUE THREAD

**Issue by santi-g-s** [kyle-n/HighlightedTextView#27]
Would it be possible to allow:
1. Changing the text editor **background colour** programatically?
2. Choose to have the text editor **adapt its height** to the content?

I'm having trouble currently doing this while its wrapped in a representable view.

Thanks for such a great repo!

**Comment by kyle-n** [comment]
For 1, pass a `@State` variable to the  `.backgroundColor()` modifier. See the [documentation](https://github.com/kyle-n/HighlightedTextEditor#modifiers-uikit). As you change the `@State` background color variable, it will change the editor's background. 

For 2, the editor will expand to fill whatever space is allotted for it. If there is more content than can fit on screen in the editor, it will scroll. This applies to the AppKit and UIKit editors. I can investigate whether it is possible to make the editor resize itself to the size of the content via a modifier, but I have no plans to release that in the immediate future.
