### ISSUE TITLE
Method missing

### ISSUE THREAD

**Issue by MiyaGrad** [kyle-n/HighlightedTextView#3]
As the other one in issue one said, There is no MarkdownTransformer and emptyUnorderedListItemRegex method in the issue one and I can not find the solution. any help please. Thank you so much.

**Comment by kyle-n** [comment]
I've left the regex I'm using on the [original thread](https://github.com/kyle-n/HighlightedTextEditor/issues/1#issuecomment-698028458).

If you have any trouble with HighlightedTextEditor, please feel free to ask. In the future, though, please only open separate issues if you have a separate problem. It's easier for me to keep track of an issue (like the regex) if the discussion of it is all on one issue 😄 .
