### ISSUE TITLE
Undo Manager

### ISSUE THREAD

**Issue by santi-g-s** [kyle-n/HighlightedTextView#34]
**Is your feature request related to a problem? Please describe.**
I'm having trouble trying to implement an undo manager for the text in the HighlightedTextEditor. 

**Describe the solution you'd like**
An undo manager built into HighlightedTextEditor which can be accessed from the environment: `@Environment(\.undoManager) var undoManager`. I believe these are built into UITextField and NSTextField [as stated here](https://developer.apple.com/documentation/uikit/uiresponder/1621122-undomanager) but the environment doesn't seem to detect an undoManager when HighlightedTextEditor is active.

**Describe alternatives you've considered**
I have tried to make an UndoProvider which wraps around the editor and passes in a binding: 

```
UndoProvider($text){ text in
     HighlightedTextEditor(text: text, highlightRules: HighlightedTextEditor.markdown)
}
```

This works but messes with selection and the insertion point location. Hence, I'm looking for an alternative that is built into the text editor itself.  

Cheers,
Santiago.

**Comment by kyle-n** [comment]
Hello, apologies for the late reply. HLTE 2.0 gives access to the whole `UITextView` or `NSTextView` via `.introspect()`. One of the properties available on `textView` is `undoManager` - is having access to that enough to solve your use case?
