### ISSUE TITLE
Value of type 'HighlightedTextEditor' has no member 'onSelectionChange'

### ISSUE THREAD

**Issue by cjhodge** [kyle-n/HighlightedTextView#40]
**Describe the bug**
TestViews.swift line 241: 
Value of type 'HighlightedTextEditor' has no member 'onSelectionChange'

**To Reproduce**
1. Download this project as a zip file.
2. Open Essayist.xcodeproj
3. Attempt to run the application.

**Expected behavior**

**Screenshots**

**Environment**
Please include:
- iOS 14.5 (iPhone 11 Pro Max simulator)
- SwiftUI

**Comment by kyle-n** [comment]
Apologies for the late response, but I am looking into this. The error is probably caused by Essayist building with too old a version of HLTE. Given that Essayist should only be built during tests, what action caused you to see this error?
