### ISSUE TITLE
Ambiguous use of 'onSelectionChange'

### ISSUE THREAD

**Issue by Yang-Xijie** [kyle-n/HighlightedTextView#48]
**Describe the bug**

I want to create the editor App for macOS. But get the error `Ambiguous use of 'onSelectionChange'` in Xcode.

**To Reproduce**

1. Go to Xcode, New Project -> macOS -> App
2. Add this package using Swift Package Manager
3. Paste below codes to `ContentView.swift`
4. See error `Ambiguous use of 'onSelectionChange'` and cannot build the project.

```swift
import SwiftUI
import HighlightedTextEditor

struct ContentView: View {
    @State var text: String = "**bold** _italic_"

    var body: some View {
        VStack {
            HighlightedTextEditor(text: $text, highlightRules: .markdown)
                // optional modifiers
                .onCommit { print("commited") }
                .onEditingChanged { print("editing changed") }
                .onTextChange { print("latest text value", $0) }
                .onSelectionChange { print("NSRange of current selection", $0) } // FIXME
                .introspect { editor in
                    // access underlying UITextView or NSTextView
                    editor.textView.backgroundColor = .white
                }
        }
    }
}
```

**Expected behavior**
I try that in iOS and it works just right. Printed out the NSRange when I make a selection.

**Screenshots**
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/57952362/121852662-627eee80-cd22-11eb-8c69-df41283facb8.png">

**Environment**
Please include:
- macOS 11.4
- Xcode 12.5
- HighlightedTextEditor 2.0.2
- Using AppKit

**Additional context**
English is not my native language; please excuse typing errors.

**Comment by kyle-n** [comment]
Apologies, this is bad documentation. Obviously you should be able to copy-paste sample code and the code should work. 

Swift is telling you it cannot automatically infer which callback you mean, so you should type your callback function. Try this:

```swift
struct ContentView: View {
    @State var text: String = "**bold** _italic_"

    var body: some View {
        VStack {
            HighlightedTextEditor(text: $text, highlightRules: .markdown)
                .onSelectionChange { (range: NSRange) in // <--------------- NSRange
                    print(range)
                }
        }
    }
}
```

I'll update the documentation if this works for you.

**Comment by kyle-n** [comment]
@Yang-Xijie Can you try the code I've provided above? Want to know if this works.

**Comment by Yang-Xijie** [comment]
Sorry for replying late. It works! Thx a lot!
😃
