### ISSUE TITLE
Regular expression error with some characters from the text in a certain encoding (for example: utf-8)

### ISSUE THREAD

**Issue by WheelaStudio** [kyle-n/HighlightedTextView#50]
**Describe the bug**
For example, if regular expression contains some symbols (e.x: И) from non-latinic alphabets(e.x: Russian) from text, which encoded in UTF-8,  an error occurs in file HighlightingTextEditor.swift on 128 line
**Error text**
HighlightedTextEditor/HighlightingTextEditor.swift:128: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2021-11-06 18:40:44.187051+0300 TextEditor[13196:2492169] HighlightedTextEditor/HighlightingTextEditor.swift:128: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**To Reproduce**
1. Bind an string, which encoded in UTF-8
2. Set in regular expression string, which contains "И"
3. See error
**Screenshots**
<img width="444" alt="image" src="https://user-images.githubusercontent.com/92257240/140615309-fe061bd6-7808-45ff-922b-bd8894e72fb6.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/92257240/140615358-9ae29d24-187d-4a5d-800d-c15c0893f3f2.png">

**Environment**
Based on SwiftUI app, running on IOS 15.1

**Comment by kyle-n** [comment]
@WheelaStudio Thanks for reporting this. I'm still working on reproducing the bug. 

This basic test project worked for me on Big Sur and iOS 15.0 in the simulator:

```swift
import SwiftUI
import HighlightedTextEditor

@main
struct TestingiOSApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

// matches text between underscores
let selection = try! NSRegularExpression(pattern: "ян", options: [])

struct ContentView: View {

    // snippets grabbed from google
    @State var text: String = "Привет Россиянин"

    var body: some View {
        VStack {
            HighlightedTextEditor(text: $text, highlightRules: [
                HighlightRule(pattern: selection, formattingRule: TextFormattingRule(key: .foregroundColor, value: UIColor.red))
            ])
        }
    }
}
```

Result: 

![simulator results](https://user-images.githubusercontent.com/13384477/141649232-c96282da-1db2-4fef-8733-d56f2d70daf8.png)

Could you modify the above code snippet so that it triggers the bug? I have a feeling I'm building the string wrong somehow.

**Comment by WheelaStudio** [comment]
I think it's problem in some files, which text was encoded incorrectly. I will check the program for another week.
