### ISSUE TITLE
[Help] How to enable HighlightedTextEditor on files open within an app.

### ISSUE THREAD

**Issue by Auratelience** [kyle-n/HighlightedTextView#57]
I am trying to create a markdown editor that can open files. How to I use HighlightedTextEditor on the files?

Thanks

**Comment by kyle-n** [comment]
HLTE edits text stored in memory in an `@State` variable. I would advise writing code outside HLTE that loads the contents of a file into your application. That data can then be edited with HLTE. I would also advise writing code to create a save button in your application that writes the content back out to a file. 

There are guides for how to do this elsewhere on the internet. File management falls outside the scope of this package.
