### ISSUE TITLE
Change selection

### ISSUE THREAD

**Issue by Urkman** [kyle-n/HighlightedTextView#61]
Is there a way to change the selection programmatically?
I made a small toolbar to format the selected text. But after the formatting, I would like to remove the current selection.
Is there a way to do this?

**Comment by kyle-n** [comment]
HLTE does not support programmatically setting the selection. 

Right now the "state" for selection is contained within the `UITextView` used within HLTE. When it changes, the new selection range is exposed to SwiftUI through the `onSelectionChange` modifier. 

If you wanted to update the selection from SwiftUI, you could probably try something with `.introspect()`.
