### ISSUE TITLE
Custom font support

### ISSUE THREAD

**Issue by mnov88** [kyle-n/HighlightedTextView#63]
Hi,

Thanks for an amazing package!
I was wondering if there are any plans to add the ability to select custom fonts and font sizes in the future? If the font is changed via TextField properties, styling stops working.
Thanks a bunch, and keep up the good work! :)

**Comment by kyle-n** [comment]
I apologize for the very long time to respond, but yes, there absolutely is a way to do this!

```swift
import SwiftUI
import HighlightedTextEditor

struct ContentView: View {
    @State private var text = "hello world"
    
    var body: some View {
        VStack {
            HighlightedTextEditor(text: $text, highlightRules: [
                HighlightRule(pattern: .all, formattingRule: TextFormattingRule(key: .font, value: NSFont.systemFont(ofSize: 45)))
            ])
        }
    }
}
```

HLTE provides `.all`, a convenience addition to `NSRegularExpression` that targets an entire string.

**Comment by runkaiz** [comment]
Is there a way for this to work in iOS? There isn't access to NSFont, so I used Font instead and the app crashes when there is any value in the editor with:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__SwiftValue _defaultLineHeightForUILayout]: unrecognized selector sent to instance 0x28308a700'
```
