### ISSUE TITLE
Hiding markdown syntax?

### ISSUE THREAD

**Issue by erikvlm** [kyle-n/HighlightedTextView#65]
Hi,

Is it possible to have the markdown hidden as the cursor "leaves", like some form of inline markdown/rich text editor mix (like Obsidian or similar note apps)?

**Comment by kyle-n** [comment]
No, sorry. I wrote this library specifically to show the formatting and markdown symbols in one editor view. It's not a feature I plan to add either.

**Comment by erikvlm** [comment]
Can you point me in what direction I can go to make that happen?

**Comment by kyle-n** [comment]
@erikvlm No, sorry. Maybe another library can do this? I don't know enough other libraries.
